# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlotMachineApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlotMachineApp

  target 'SlotMachineAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftConfettiView'

  target 'SlotMachineAppUITests' do
    # Pods for testing
  end

end
